//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncPiwikToMSSQL.PromotionReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PromotionReference.IPromotionEngineService")]
    public interface IPromotionEngineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionEngineService/Display", ReplyAction="http://tempuri.org/IPromotionEngineService/DisplayResponse")]
        Boodoll.WCFProvider.PromotionReference.PromotionResponse Display(Boodoll.WCFProvider.PromotionReference.PromotionRequest pa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionEngineService/Exec", ReplyAction="http://tempuri.org/IPromotionEngineService/ExecResponse")]
        Boodoll.WCFProvider.PromotionReference.PromotionResponse Exec(Boodoll.WCFProvider.PromotionReference.PromotionRequest pa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPromotionEngineService/ClearCache", ReplyAction="http://tempuri.org/IPromotionEngineService/ClearCacheResponse")]
        Boodoll.WCFProvider.PromotionReference.PromotionResponse ClearCache(int PromotionID, string PromotionType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPromotionEngineServiceChannel : SyncPiwikToMSSQL.PromotionReference.IPromotionEngineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PromotionEngineServiceClient : System.ServiceModel.ClientBase<SyncPiwikToMSSQL.PromotionReference.IPromotionEngineService>, SyncPiwikToMSSQL.PromotionReference.IPromotionEngineService {
        
        public PromotionEngineServiceClient() {
        }
        
        public PromotionEngineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PromotionEngineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionEngineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromotionEngineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Boodoll.WCFProvider.PromotionReference.PromotionResponse Display(Boodoll.WCFProvider.PromotionReference.PromotionRequest pa) {
            return base.Channel.Display(pa);
        }
        
        public Boodoll.WCFProvider.PromotionReference.PromotionResponse Exec(Boodoll.WCFProvider.PromotionReference.PromotionRequest pa) {
            return base.Channel.Exec(pa);
        }
        
        public Boodoll.WCFProvider.PromotionReference.PromotionResponse ClearCache(int PromotionID, string PromotionType) {
            return base.Channel.ClearCache(PromotionID, PromotionType);
        }
    }
}
