<?xml version="1.0" encoding="utf-8"?>
<Database Name="offLineBBHome" Class="OffBbhomeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.100.242\myzjdw2008;Initial Catalog=offLineBBHome;Persist Security Info=True;User ID=sa" SettingsObjectName="SyncDataBll.Properties.Settings" SettingsPropertyName="offLineBBHomeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Piwik_ColumnWord" Member="Piwik_ColumnWords">
    <Type Name="Piwik_ColumnWord">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="refferurl" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="refferurlUTF" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Piwik_log" Member="Piwik_logs">
    <Type Name="Piwik_log">
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="guid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="url" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="lastVisitTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="action" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pagetitle" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="spenttime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="refferurl" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="event_action" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="visitIp" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="locationsina" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Piwik_CustomerAction" Member="Piwik_CustomerActions">
    <Type Name="Piwik_CustomerAction">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="label" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="nb_actions" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idsubdatatable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>