#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5448
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="bbHome")]
	public partial class BbhomeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbase_t_member(base_t_member instance);
    partial void Updatebase_t_member(base_t_member instance);
    partial void Deletebase_t_member(base_t_member instance);
    #endregion
		
		public BbhomeDataContext() : 
				base(global::ConsoleApplication2.Properties.Settings.Default.bbHomeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BbhomeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BbhomeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BbhomeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BbhomeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<base_t_member> base_t_members
		{
			get
			{
				return this.GetTable<base_t_member>();
			}
		}
	}
	
	[Table(Name="dbo.base_t_member")]
	public partial class base_t_member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _membNo;
		
		private string _userCode;
		
		private string _userName;
		
		private System.Nullable<System.DateTime> _regTime;
		
		private string _createBy;
		
		private System.Nullable<System.DateTime> _updateTime;
		
		private string _updateBy;
		
		private string _cardNO;
		
		private System.Nullable<int> _noteFlag;
		
		private System.Nullable<int> _userGroupId;
		
		private System.Nullable<int> _policymaker;
		
		private System.Nullable<int> _ReferrerMembNo;
		
		private System.Nullable<int> _province;
		
		private System.Nullable<int> _city;
		
		private System.Nullable<int> _district;
		
		private System.Nullable<int> _scores;
		
		private System.Nullable<int> _valid;
		
		private string _mobileTel;
		
		private string _tel;
		
		private string _email;
		
		private System.Nullable<int> _userLevel;
		
		private System.Nullable<int> _areaNo;
		
		private System.Nullable<int> _regType;
		
		private System.Nullable<int> _clusterId;
		
		private System.Nullable<int> _regFrom;
		
		private string _passward;
		
		private string _nickName;
		
		private System.Nullable<byte> _sex;
		
		private string _question;
		
		private string _answer;
		
		private string _qq;
		
		private string _msn;
		
		private System.Nullable<int> _beValidate;
		
		private int _orderTimes;
		
		private System.Nullable<int> _intUserType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmembNoChanging(int value);
    partial void OnmembNoChanged();
    partial void OnuserCodeChanging(string value);
    partial void OnuserCodeChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnregTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnregTimeChanged();
    partial void OncreateByChanging(string value);
    partial void OncreateByChanged();
    partial void OnupdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnupdateTimeChanged();
    partial void OnupdateByChanging(string value);
    partial void OnupdateByChanged();
    partial void OncardNOChanging(string value);
    partial void OncardNOChanged();
    partial void OnnoteFlagChanging(System.Nullable<int> value);
    partial void OnnoteFlagChanged();
    partial void OnuserGroupIdChanging(System.Nullable<int> value);
    partial void OnuserGroupIdChanged();
    partial void OnpolicymakerChanging(System.Nullable<int> value);
    partial void OnpolicymakerChanged();
    partial void OnReferrerMembNoChanging(System.Nullable<int> value);
    partial void OnReferrerMembNoChanged();
    partial void OnprovinceChanging(System.Nullable<int> value);
    partial void OnprovinceChanged();
    partial void OncityChanging(System.Nullable<int> value);
    partial void OncityChanged();
    partial void OndistrictChanging(System.Nullable<int> value);
    partial void OndistrictChanged();
    partial void OnscoresChanging(System.Nullable<int> value);
    partial void OnscoresChanged();
    partial void OnvalidChanging(System.Nullable<int> value);
    partial void OnvalidChanged();
    partial void OnmobileTelChanging(string value);
    partial void OnmobileTelChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnuserLevelChanging(System.Nullable<int> value);
    partial void OnuserLevelChanged();
    partial void OnareaNoChanging(System.Nullable<int> value);
    partial void OnareaNoChanged();
    partial void OnregTypeChanging(System.Nullable<int> value);
    partial void OnregTypeChanged();
    partial void OnclusterIdChanging(System.Nullable<int> value);
    partial void OnclusterIdChanged();
    partial void OnregFromChanging(System.Nullable<int> value);
    partial void OnregFromChanged();
    partial void OnpasswardChanging(string value);
    partial void OnpasswardChanged();
    partial void OnnickNameChanging(string value);
    partial void OnnickNameChanged();
    partial void OnsexChanging(System.Nullable<byte> value);
    partial void OnsexChanged();
    partial void OnquestionChanging(string value);
    partial void OnquestionChanged();
    partial void OnanswerChanging(string value);
    partial void OnanswerChanged();
    partial void OnqqChanging(string value);
    partial void OnqqChanged();
    partial void OnmsnChanging(string value);
    partial void OnmsnChanged();
    partial void OnbeValidateChanging(System.Nullable<int> value);
    partial void OnbeValidateChanged();
    partial void OnorderTimesChanging(int value);
    partial void OnorderTimesChanged();
    partial void OnintUserTypeChanging(System.Nullable<int> value);
    partial void OnintUserTypeChanged();
    #endregion
		
		public base_t_member()
		{
			OnCreated();
		}
		
		[Column(Storage="_membNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int membNo
		{
			get
			{
				return this._membNo;
			}
			set
			{
				if ((this._membNo != value))
				{
					this.OnmembNoChanging(value);
					this.SendPropertyChanging();
					this._membNo = value;
					this.SendPropertyChanged("membNo");
					this.OnmembNoChanged();
				}
			}
		}
		
		[Column(Storage="_userCode", DbType="VarChar(30)")]
		public string userCode
		{
			get
			{
				return this._userCode;
			}
			set
			{
				if ((this._userCode != value))
				{
					this.OnuserCodeChanging(value);
					this.SendPropertyChanging();
					this._userCode = value;
					this.SendPropertyChanged("userCode");
					this.OnuserCodeChanged();
				}
			}
		}
		
		[Column(Storage="_userName", DbType="VarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[Column(Storage="_regTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> regTime
		{
			get
			{
				return this._regTime;
			}
			set
			{
				if ((this._regTime != value))
				{
					this.OnregTimeChanging(value);
					this.SendPropertyChanging();
					this._regTime = value;
					this.SendPropertyChanged("regTime");
					this.OnregTimeChanged();
				}
			}
		}
		
		[Column(Storage="_createBy", DbType="Char(10)")]
		public string createBy
		{
			get
			{
				return this._createBy;
			}
			set
			{
				if ((this._createBy != value))
				{
					this.OncreateByChanging(value);
					this.SendPropertyChanging();
					this._createBy = value;
					this.SendPropertyChanged("createBy");
					this.OncreateByChanged();
				}
			}
		}
		
		[Column(Storage="_updateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> updateTime
		{
			get
			{
				return this._updateTime;
			}
			set
			{
				if ((this._updateTime != value))
				{
					this.OnupdateTimeChanging(value);
					this.SendPropertyChanging();
					this._updateTime = value;
					this.SendPropertyChanged("updateTime");
					this.OnupdateTimeChanged();
				}
			}
		}
		
		[Column(Storage="_updateBy", DbType="VarChar(10)")]
		public string updateBy
		{
			get
			{
				return this._updateBy;
			}
			set
			{
				if ((this._updateBy != value))
				{
					this.OnupdateByChanging(value);
					this.SendPropertyChanging();
					this._updateBy = value;
					this.SendPropertyChanged("updateBy");
					this.OnupdateByChanged();
				}
			}
		}
		
		[Column(Storage="_cardNO", DbType="VarChar(50)")]
		public string cardNO
		{
			get
			{
				return this._cardNO;
			}
			set
			{
				if ((this._cardNO != value))
				{
					this.OncardNOChanging(value);
					this.SendPropertyChanging();
					this._cardNO = value;
					this.SendPropertyChanged("cardNO");
					this.OncardNOChanged();
				}
			}
		}
		
		[Column(Storage="_noteFlag", DbType="Int")]
		public System.Nullable<int> noteFlag
		{
			get
			{
				return this._noteFlag;
			}
			set
			{
				if ((this._noteFlag != value))
				{
					this.OnnoteFlagChanging(value);
					this.SendPropertyChanging();
					this._noteFlag = value;
					this.SendPropertyChanged("noteFlag");
					this.OnnoteFlagChanged();
				}
			}
		}
		
		[Column(Storage="_userGroupId", DbType="Int")]
		public System.Nullable<int> userGroupId
		{
			get
			{
				return this._userGroupId;
			}
			set
			{
				if ((this._userGroupId != value))
				{
					this.OnuserGroupIdChanging(value);
					this.SendPropertyChanging();
					this._userGroupId = value;
					this.SendPropertyChanged("userGroupId");
					this.OnuserGroupIdChanged();
				}
			}
		}
		
		[Column(Storage="_policymaker", DbType="Int")]
		public System.Nullable<int> policymaker
		{
			get
			{
				return this._policymaker;
			}
			set
			{
				if ((this._policymaker != value))
				{
					this.OnpolicymakerChanging(value);
					this.SendPropertyChanging();
					this._policymaker = value;
					this.SendPropertyChanged("policymaker");
					this.OnpolicymakerChanged();
				}
			}
		}
		
		[Column(Storage="_ReferrerMembNo", DbType="Int")]
		public System.Nullable<int> ReferrerMembNo
		{
			get
			{
				return this._ReferrerMembNo;
			}
			set
			{
				if ((this._ReferrerMembNo != value))
				{
					this.OnReferrerMembNoChanging(value);
					this.SendPropertyChanging();
					this._ReferrerMembNo = value;
					this.SendPropertyChanged("ReferrerMembNo");
					this.OnReferrerMembNoChanged();
				}
			}
		}
		
		[Column(Storage="_province", DbType="Int")]
		public System.Nullable<int> province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[Column(Storage="_city", DbType="Int")]
		public System.Nullable<int> city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[Column(Storage="_district", DbType="Int")]
		public System.Nullable<int> district
		{
			get
			{
				return this._district;
			}
			set
			{
				if ((this._district != value))
				{
					this.OndistrictChanging(value);
					this.SendPropertyChanging();
					this._district = value;
					this.SendPropertyChanged("district");
					this.OndistrictChanged();
				}
			}
		}
		
		[Column(Storage="_scores", DbType="Int")]
		public System.Nullable<int> scores
		{
			get
			{
				return this._scores;
			}
			set
			{
				if ((this._scores != value))
				{
					this.OnscoresChanging(value);
					this.SendPropertyChanging();
					this._scores = value;
					this.SendPropertyChanged("scores");
					this.OnscoresChanged();
				}
			}
		}
		
		[Column(Storage="_valid", DbType="Int")]
		public System.Nullable<int> valid
		{
			get
			{
				return this._valid;
			}
			set
			{
				if ((this._valid != value))
				{
					this.OnvalidChanging(value);
					this.SendPropertyChanging();
					this._valid = value;
					this.SendPropertyChanged("valid");
					this.OnvalidChanged();
				}
			}
		}
		
		[Column(Storage="_mobileTel", DbType="VarChar(20)")]
		public string mobileTel
		{
			get
			{
				return this._mobileTel;
			}
			set
			{
				if ((this._mobileTel != value))
				{
					this.OnmobileTelChanging(value);
					this.SendPropertyChanging();
					this._mobileTel = value;
					this.SendPropertyChanged("mobileTel");
					this.OnmobileTelChanged();
				}
			}
		}
		
		[Column(Storage="_tel", DbType="VarChar(20)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_userLevel", DbType="Int")]
		public System.Nullable<int> userLevel
		{
			get
			{
				return this._userLevel;
			}
			set
			{
				if ((this._userLevel != value))
				{
					this.OnuserLevelChanging(value);
					this.SendPropertyChanging();
					this._userLevel = value;
					this.SendPropertyChanged("userLevel");
					this.OnuserLevelChanged();
				}
			}
		}
		
		[Column(Storage="_areaNo", DbType="Int")]
		public System.Nullable<int> areaNo
		{
			get
			{
				return this._areaNo;
			}
			set
			{
				if ((this._areaNo != value))
				{
					this.OnareaNoChanging(value);
					this.SendPropertyChanging();
					this._areaNo = value;
					this.SendPropertyChanged("areaNo");
					this.OnareaNoChanged();
				}
			}
		}
		
		[Column(Storage="_regType", DbType="Int")]
		public System.Nullable<int> regType
		{
			get
			{
				return this._regType;
			}
			set
			{
				if ((this._regType != value))
				{
					this.OnregTypeChanging(value);
					this.SendPropertyChanging();
					this._regType = value;
					this.SendPropertyChanged("regType");
					this.OnregTypeChanged();
				}
			}
		}
		
		[Column(Storage="_clusterId", DbType="Int")]
		public System.Nullable<int> clusterId
		{
			get
			{
				return this._clusterId;
			}
			set
			{
				if ((this._clusterId != value))
				{
					this.OnclusterIdChanging(value);
					this.SendPropertyChanging();
					this._clusterId = value;
					this.SendPropertyChanged("clusterId");
					this.OnclusterIdChanged();
				}
			}
		}
		
		[Column(Storage="_regFrom", DbType="Int")]
		public System.Nullable<int> regFrom
		{
			get
			{
				return this._regFrom;
			}
			set
			{
				if ((this._regFrom != value))
				{
					this.OnregFromChanging(value);
					this.SendPropertyChanging();
					this._regFrom = value;
					this.SendPropertyChanged("regFrom");
					this.OnregFromChanged();
				}
			}
		}
		
		[Column(Storage="_passward", DbType="NVarChar(50)")]
		public string passward
		{
			get
			{
				return this._passward;
			}
			set
			{
				if ((this._passward != value))
				{
					this.OnpasswardChanging(value);
					this.SendPropertyChanging();
					this._passward = value;
					this.SendPropertyChanged("passward");
					this.OnpasswardChanged();
				}
			}
		}
		
		[Column(Storage="_nickName", DbType="NVarChar(50)")]
		public string nickName
		{
			get
			{
				return this._nickName;
			}
			set
			{
				if ((this._nickName != value))
				{
					this.OnnickNameChanging(value);
					this.SendPropertyChanging();
					this._nickName = value;
					this.SendPropertyChanged("nickName");
					this.OnnickNameChanged();
				}
			}
		}
		
		[Column(Storage="_sex", DbType="TinyInt")]
		public System.Nullable<byte> sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[Column(Storage="_question", DbType="NVarChar(100)")]
		public string question
		{
			get
			{
				return this._question;
			}
			set
			{
				if ((this._question != value))
				{
					this.OnquestionChanging(value);
					this.SendPropertyChanging();
					this._question = value;
					this.SendPropertyChanged("question");
					this.OnquestionChanged();
				}
			}
		}
		
		[Column(Storage="_answer", DbType="NVarChar(100)")]
		public string answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				if ((this._answer != value))
				{
					this.OnanswerChanging(value);
					this.SendPropertyChanging();
					this._answer = value;
					this.SendPropertyChanged("answer");
					this.OnanswerChanged();
				}
			}
		}
		
		[Column(Storage="_qq", DbType="NVarChar(50)")]
		public string qq
		{
			get
			{
				return this._qq;
			}
			set
			{
				if ((this._qq != value))
				{
					this.OnqqChanging(value);
					this.SendPropertyChanging();
					this._qq = value;
					this.SendPropertyChanged("qq");
					this.OnqqChanged();
				}
			}
		}
		
		[Column(Storage="_msn", DbType="NVarChar(50)")]
		public string msn
		{
			get
			{
				return this._msn;
			}
			set
			{
				if ((this._msn != value))
				{
					this.OnmsnChanging(value);
					this.SendPropertyChanging();
					this._msn = value;
					this.SendPropertyChanged("msn");
					this.OnmsnChanged();
				}
			}
		}
		
		[Column(Storage="_beValidate", DbType="Int")]
		public System.Nullable<int> beValidate
		{
			get
			{
				return this._beValidate;
			}
			set
			{
				if ((this._beValidate != value))
				{
					this.OnbeValidateChanging(value);
					this.SendPropertyChanging();
					this._beValidate = value;
					this.SendPropertyChanged("beValidate");
					this.OnbeValidateChanged();
				}
			}
		}
		
		[Column(Storage="_orderTimes", DbType="Int NOT NULL")]
		public int orderTimes
		{
			get
			{
				return this._orderTimes;
			}
			set
			{
				if ((this._orderTimes != value))
				{
					this.OnorderTimesChanging(value);
					this.SendPropertyChanging();
					this._orderTimes = value;
					this.SendPropertyChanged("orderTimes");
					this.OnorderTimesChanged();
				}
			}
		}
		
		[Column(Storage="_intUserType", DbType="Int")]
		public System.Nullable<int> intUserType
		{
			get
			{
				return this._intUserType;
			}
			set
			{
				if ((this._intUserType != value))
				{
					this.OnintUserTypeChanging(value);
					this.SendPropertyChanging();
					this._intUserType = value;
					this.SendPropertyChanged("intUserType");
					this.OnintUserTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
