#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncPiwikToMSSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Holyca")]
	public partial class HolycaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertPdt_Base_Info(Pdt_Base_Info instance);
    partial void UpdatePdt_Base_Info(Pdt_Base_Info instance);
    partial void DeletePdt_Base_Info(Pdt_Base_Info instance);
    #endregion
		
		public HolycaDataContext() : 
				base(global::SyncPiwikToMSSQL.Properties.Settings.Default.HolycaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HolycaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HolycaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HolycaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HolycaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vi_Web_Pdt_AllList> Vi_Web_Pdt_AllLists
		{
			get
			{
				return this.GetTable<Vi_Web_Pdt_AllList>();
			}
		}
		
		public System.Data.Linq.Table<Vi_Web_Pdt_List> Vi_Web_Pdt_Lists
		{
			get
			{
				return this.GetTable<Vi_Web_Pdt_List>();
			}
		}
		
		public System.Data.Linq.Table<Vi_Web_Pdt_Detail> Vi_Web_Pdt_Details
		{
			get
			{
				return this.GetTable<Vi_Web_Pdt_Detail>();
			}
		}
		
		public System.Data.Linq.Table<Pdt_Base_Info> Pdt_Base_Infos
		{
			get
			{
				return this.GetTable<Pdt_Base_Info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vi_Web_Pdt_AllList")]
	public partial class Vi_Web_Pdt_AllList
	{
		
		private System.Nullable<int> _intIsGroup;
		
		private string _vchProductName;
		
		private string _vchMainPicURL;
		
		private int _intProductID;
		
		private System.Nullable<decimal> _numMarketPrice;
		
		private System.Nullable<decimal> _numVipPrice;
		
		private System.Nullable<decimal> _numCost;
		
		private System.Nullable<decimal> _numCleanCost;
		
		private System.Nullable<int> _intIsNew;
		
		private System.Nullable<int> _intIsProm;
		
		private int _intBrandID;
		
		private string _vchProductPrinted;
		
		private string _vchBrandName;
		
		private int _intWebType;
		
		private string _vchCateName;
		
		private int _intWebChildType;
		
		private System.Nullable<int> _intWebThirdType;
		
		private string _vchCateChildName;
		
		private int _intFirstCategory;
		
		private int _intSecondCategory;
		
		private int _intThreeCategory;
		
		private System.Nullable<short> _intStartAge;
		
		private System.Nullable<short> _intEndAge;
		
		private int _intChannelID;
		
		private short _intHerdID;
		
		private System.Nullable<int> _intScore;
		
		private decimal _numHerdPrice;
		
		private System.Nullable<int> _intAreaID;
		
		private System.Nullable<int> _intStockQty;
		
		private System.Nullable<int> _intGroupID;
		
		private System.Nullable<int> _intCommentVolume;
		
		private System.Nullable<int> _intSalesVolume;
		
		private string _vchShortName;
		
		public Vi_Web_Pdt_AllList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsGroup", DbType="Int")]
		public System.Nullable<int> intIsGroup
		{
			get
			{
				return this._intIsGroup;
			}
			set
			{
				if ((this._intIsGroup != value))
				{
					this._intIsGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductName", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string vchProductName
		{
			get
			{
				return this._vchProductName;
			}
			set
			{
				if ((this._vchProductName != value))
				{
					this._vchProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMainPicURL", DbType="VarChar(128)")]
		public string vchMainPicURL
		{
			get
			{
				return this._vchMainPicURL;
			}
			set
			{
				if ((this._vchMainPicURL != value))
				{
					this._vchMainPicURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intProductID", DbType="Int NOT NULL")]
		public int intProductID
		{
			get
			{
				return this._intProductID;
			}
			set
			{
				if ((this._intProductID != value))
				{
					this._intProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMarketPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> numMarketPrice
		{
			get
			{
				return this._numMarketPrice;
			}
			set
			{
				if ((this._numMarketPrice != value))
				{
					this._numMarketPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVipPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> numVipPrice
		{
			get
			{
				return this._numVipPrice;
			}
			set
			{
				if ((this._numVipPrice != value))
				{
					this._numVipPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCost", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> numCost
		{
			get
			{
				return this._numCost;
			}
			set
			{
				if ((this._numCost != value))
				{
					this._numCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCleanCost", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> numCleanCost
		{
			get
			{
				return this._numCleanCost;
			}
			set
			{
				if ((this._numCleanCost != value))
				{
					this._numCleanCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsNew", DbType="Int")]
		public System.Nullable<int> intIsNew
		{
			get
			{
				return this._intIsNew;
			}
			set
			{
				if ((this._intIsNew != value))
				{
					this._intIsNew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsProm", DbType="Int")]
		public System.Nullable<int> intIsProm
		{
			get
			{
				return this._intIsProm;
			}
			set
			{
				if ((this._intIsProm != value))
				{
					this._intIsProm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intBrandID", DbType="Int NOT NULL")]
		public int intBrandID
		{
			get
			{
				return this._intBrandID;
			}
			set
			{
				if ((this._intBrandID != value))
				{
					this._intBrandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductPrinted", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string vchProductPrinted
		{
			get
			{
				return this._vchProductPrinted;
			}
			set
			{
				if ((this._vchProductPrinted != value))
				{
					this._vchProductPrinted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchBrandName", DbType="NVarChar(25)")]
		public string vchBrandName
		{
			get
			{
				return this._vchBrandName;
			}
			set
			{
				if ((this._vchBrandName != value))
				{
					this._vchBrandName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebType", DbType="Int NOT NULL")]
		public int intWebType
		{
			get
			{
				return this._intWebType;
			}
			set
			{
				if ((this._intWebType != value))
				{
					this._intWebType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCateName", DbType="NVarChar(32)")]
		public string vchCateName
		{
			get
			{
				return this._vchCateName;
			}
			set
			{
				if ((this._vchCateName != value))
				{
					this._vchCateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebChildType", DbType="Int NOT NULL")]
		public int intWebChildType
		{
			get
			{
				return this._intWebChildType;
			}
			set
			{
				if ((this._intWebChildType != value))
				{
					this._intWebChildType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebThirdType", DbType="Int")]
		public System.Nullable<int> intWebThirdType
		{
			get
			{
				return this._intWebThirdType;
			}
			set
			{
				if ((this._intWebThirdType != value))
				{
					this._intWebThirdType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCateChildName", DbType="NVarChar(32)")]
		public string vchCateChildName
		{
			get
			{
				return this._vchCateChildName;
			}
			set
			{
				if ((this._vchCateChildName != value))
				{
					this._vchCateChildName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intFirstCategory", DbType="Int NOT NULL")]
		public int intFirstCategory
		{
			get
			{
				return this._intFirstCategory;
			}
			set
			{
				if ((this._intFirstCategory != value))
				{
					this._intFirstCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSecondCategory", DbType="Int NOT NULL")]
		public int intSecondCategory
		{
			get
			{
				return this._intSecondCategory;
			}
			set
			{
				if ((this._intSecondCategory != value))
				{
					this._intSecondCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intThreeCategory", DbType="Int NOT NULL")]
		public int intThreeCategory
		{
			get
			{
				return this._intThreeCategory;
			}
			set
			{
				if ((this._intThreeCategory != value))
				{
					this._intThreeCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intStartAge", DbType="SmallInt")]
		public System.Nullable<short> intStartAge
		{
			get
			{
				return this._intStartAge;
			}
			set
			{
				if ((this._intStartAge != value))
				{
					this._intStartAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intEndAge", DbType="SmallInt")]
		public System.Nullable<short> intEndAge
		{
			get
			{
				return this._intEndAge;
			}
			set
			{
				if ((this._intEndAge != value))
				{
					this._intEndAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intChannelID", DbType="Int NOT NULL")]
		public int intChannelID
		{
			get
			{
				return this._intChannelID;
			}
			set
			{
				if ((this._intChannelID != value))
				{
					this._intChannelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intHerdID", DbType="SmallInt NOT NULL")]
		public short intHerdID
		{
			get
			{
				return this._intHerdID;
			}
			set
			{
				if ((this._intHerdID != value))
				{
					this._intHerdID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intScore", DbType="Int")]
		public System.Nullable<int> intScore
		{
			get
			{
				return this._intScore;
			}
			set
			{
				if ((this._intScore != value))
				{
					this._intScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numHerdPrice", DbType="Decimal(10,2) NOT NULL")]
		public decimal numHerdPrice
		{
			get
			{
				return this._numHerdPrice;
			}
			set
			{
				if ((this._numHerdPrice != value))
				{
					this._numHerdPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAreaID", DbType="Int")]
		public System.Nullable<int> intAreaID
		{
			get
			{
				return this._intAreaID;
			}
			set
			{
				if ((this._intAreaID != value))
				{
					this._intAreaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intStockQty", DbType="Int")]
		public System.Nullable<int> intStockQty
		{
			get
			{
				return this._intStockQty;
			}
			set
			{
				if ((this._intStockQty != value))
				{
					this._intStockQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intGroupID", DbType="Int")]
		public System.Nullable<int> intGroupID
		{
			get
			{
				return this._intGroupID;
			}
			set
			{
				if ((this._intGroupID != value))
				{
					this._intGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCommentVolume", DbType="Int")]
		public System.Nullable<int> intCommentVolume
		{
			get
			{
				return this._intCommentVolume;
			}
			set
			{
				if ((this._intCommentVolume != value))
				{
					this._intCommentVolume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSalesVolume", DbType="Int")]
		public System.Nullable<int> intSalesVolume
		{
			get
			{
				return this._intSalesVolume;
			}
			set
			{
				if ((this._intSalesVolume != value))
				{
					this._intSalesVolume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchShortName", DbType="NVarChar(32)")]
		public string vchShortName
		{
			get
			{
				return this._vchShortName;
			}
			set
			{
				if ((this._vchShortName != value))
				{
					this._vchShortName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vi_Web_Pdt_List")]
	public partial class Vi_Web_Pdt_List
	{
		
		private string _vchProductName;
		
		private string _vchMainPicURL;
		
		private int _intProductID;
		
		private System.Nullable<decimal> _numMarketPrice;
		
		private System.Nullable<decimal> _numVipPrice;
		
		private System.Nullable<decimal> _numCost;
		
		private System.Nullable<decimal> _numCleanCost;
		
		private System.Nullable<int> _intIsNew;
		
		private System.Nullable<int> _intIsProm;
		
		private int _intBrandID;
		
		private string _vchProductPrinted;
		
		private string _vchBrandName;
		
		private int _intWebType;
		
		private string _vchCateName;
		
		private int _intWebChildType;
		
		private System.Nullable<int> _intWebThirdType;
		
		private string _vchCateChildName;
		
		private int _intFirstCategory;
		
		private int _intSecondCategory;
		
		private int _intThreeCategory;
		
		private System.Nullable<short> _intStartAge;
		
		private System.Nullable<short> _intEndAge;
		
		private int _intChannelID;
		
		private short _intHerdID;
		
		private System.Nullable<int> _intScore;
		
		private decimal _numHerdPrice;
		
		private System.Nullable<int> _intAreaID;
		
		private System.Nullable<int> _intStockQty;
		
		private System.Nullable<int> _intGroupID;
		
		private System.Nullable<int> _intCommentVolume;
		
		private System.Nullable<int> _intSalesVolume;
		
		private string _vchShortName;
		
		public Vi_Web_Pdt_List()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductName", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string vchProductName
		{
			get
			{
				return this._vchProductName;
			}
			set
			{
				if ((this._vchProductName != value))
				{
					this._vchProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMainPicURL", DbType="VarChar(128)")]
		public string vchMainPicURL
		{
			get
			{
				return this._vchMainPicURL;
			}
			set
			{
				if ((this._vchMainPicURL != value))
				{
					this._vchMainPicURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intProductID", DbType="Int NOT NULL")]
		public int intProductID
		{
			get
			{
				return this._intProductID;
			}
			set
			{
				if ((this._intProductID != value))
				{
					this._intProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMarketPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> numMarketPrice
		{
			get
			{
				return this._numMarketPrice;
			}
			set
			{
				if ((this._numMarketPrice != value))
				{
					this._numMarketPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVipPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> numVipPrice
		{
			get
			{
				return this._numVipPrice;
			}
			set
			{
				if ((this._numVipPrice != value))
				{
					this._numVipPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCost", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> numCost
		{
			get
			{
				return this._numCost;
			}
			set
			{
				if ((this._numCost != value))
				{
					this._numCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCleanCost", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> numCleanCost
		{
			get
			{
				return this._numCleanCost;
			}
			set
			{
				if ((this._numCleanCost != value))
				{
					this._numCleanCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsNew", DbType="Int")]
		public System.Nullable<int> intIsNew
		{
			get
			{
				return this._intIsNew;
			}
			set
			{
				if ((this._intIsNew != value))
				{
					this._intIsNew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsProm", DbType="Int")]
		public System.Nullable<int> intIsProm
		{
			get
			{
				return this._intIsProm;
			}
			set
			{
				if ((this._intIsProm != value))
				{
					this._intIsProm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intBrandID", DbType="Int NOT NULL")]
		public int intBrandID
		{
			get
			{
				return this._intBrandID;
			}
			set
			{
				if ((this._intBrandID != value))
				{
					this._intBrandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductPrinted", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string vchProductPrinted
		{
			get
			{
				return this._vchProductPrinted;
			}
			set
			{
				if ((this._vchProductPrinted != value))
				{
					this._vchProductPrinted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchBrandName", DbType="NVarChar(25)")]
		public string vchBrandName
		{
			get
			{
				return this._vchBrandName;
			}
			set
			{
				if ((this._vchBrandName != value))
				{
					this._vchBrandName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebType", DbType="Int NOT NULL")]
		public int intWebType
		{
			get
			{
				return this._intWebType;
			}
			set
			{
				if ((this._intWebType != value))
				{
					this._intWebType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCateName", DbType="NVarChar(32)")]
		public string vchCateName
		{
			get
			{
				return this._vchCateName;
			}
			set
			{
				if ((this._vchCateName != value))
				{
					this._vchCateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebChildType", DbType="Int NOT NULL")]
		public int intWebChildType
		{
			get
			{
				return this._intWebChildType;
			}
			set
			{
				if ((this._intWebChildType != value))
				{
					this._intWebChildType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebThirdType", DbType="Int")]
		public System.Nullable<int> intWebThirdType
		{
			get
			{
				return this._intWebThirdType;
			}
			set
			{
				if ((this._intWebThirdType != value))
				{
					this._intWebThirdType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCateChildName", DbType="NVarChar(32)")]
		public string vchCateChildName
		{
			get
			{
				return this._vchCateChildName;
			}
			set
			{
				if ((this._vchCateChildName != value))
				{
					this._vchCateChildName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intFirstCategory", DbType="Int NOT NULL")]
		public int intFirstCategory
		{
			get
			{
				return this._intFirstCategory;
			}
			set
			{
				if ((this._intFirstCategory != value))
				{
					this._intFirstCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSecondCategory", DbType="Int NOT NULL")]
		public int intSecondCategory
		{
			get
			{
				return this._intSecondCategory;
			}
			set
			{
				if ((this._intSecondCategory != value))
				{
					this._intSecondCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intThreeCategory", DbType="Int NOT NULL")]
		public int intThreeCategory
		{
			get
			{
				return this._intThreeCategory;
			}
			set
			{
				if ((this._intThreeCategory != value))
				{
					this._intThreeCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intStartAge", DbType="SmallInt")]
		public System.Nullable<short> intStartAge
		{
			get
			{
				return this._intStartAge;
			}
			set
			{
				if ((this._intStartAge != value))
				{
					this._intStartAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intEndAge", DbType="SmallInt")]
		public System.Nullable<short> intEndAge
		{
			get
			{
				return this._intEndAge;
			}
			set
			{
				if ((this._intEndAge != value))
				{
					this._intEndAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intChannelID", DbType="Int NOT NULL")]
		public int intChannelID
		{
			get
			{
				return this._intChannelID;
			}
			set
			{
				if ((this._intChannelID != value))
				{
					this._intChannelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intHerdID", DbType="SmallInt NOT NULL")]
		public short intHerdID
		{
			get
			{
				return this._intHerdID;
			}
			set
			{
				if ((this._intHerdID != value))
				{
					this._intHerdID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intScore", DbType="Int")]
		public System.Nullable<int> intScore
		{
			get
			{
				return this._intScore;
			}
			set
			{
				if ((this._intScore != value))
				{
					this._intScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numHerdPrice", DbType="Decimal(10,2) NOT NULL")]
		public decimal numHerdPrice
		{
			get
			{
				return this._numHerdPrice;
			}
			set
			{
				if ((this._numHerdPrice != value))
				{
					this._numHerdPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAreaID", DbType="Int")]
		public System.Nullable<int> intAreaID
		{
			get
			{
				return this._intAreaID;
			}
			set
			{
				if ((this._intAreaID != value))
				{
					this._intAreaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intStockQty", DbType="Int")]
		public System.Nullable<int> intStockQty
		{
			get
			{
				return this._intStockQty;
			}
			set
			{
				if ((this._intStockQty != value))
				{
					this._intStockQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intGroupID", DbType="Int")]
		public System.Nullable<int> intGroupID
		{
			get
			{
				return this._intGroupID;
			}
			set
			{
				if ((this._intGroupID != value))
				{
					this._intGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCommentVolume", DbType="Int")]
		public System.Nullable<int> intCommentVolume
		{
			get
			{
				return this._intCommentVolume;
			}
			set
			{
				if ((this._intCommentVolume != value))
				{
					this._intCommentVolume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSalesVolume", DbType="Int")]
		public System.Nullable<int> intSalesVolume
		{
			get
			{
				return this._intSalesVolume;
			}
			set
			{
				if ((this._intSalesVolume != value))
				{
					this._intSalesVolume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchShortName", DbType="NVarChar(32)")]
		public string vchShortName
		{
			get
			{
				return this._vchShortName;
			}
			set
			{
				if ((this._vchShortName != value))
				{
					this._vchShortName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vi_Web_Pdt_Detail")]
	public partial class Vi_Web_Pdt_Detail
	{
		
		private string _vchProductName;
		
		private string _vchMainPicURL;
		
		private int _intProductID;
		
		private System.Nullable<int> _intGroupID;
		
		private System.Nullable<int> _intIsNew;
		
		private System.Nullable<int> _intIsProm;
		
		private int _intBrandID;
		
		private int _intWebType;
		
		private int _intWebChildType;
		
		private System.Nullable<int> _intWebThirdType;
		
		private int _intFirstCategory;
		
		private int _intSecondCategory;
		
		private int _intThreeCategory;
		
		private System.Nullable<short> _intStartAge;
		
		private System.Nullable<short> _intEndAge;
		
		private string _vchProColr;
		
		private string _vchSpec;
		
		private string _vchProductPrinted;
		
		private int _intAttribute;
		
		private System.Nullable<decimal> _numMarketPrice;
		
		private System.Nullable<decimal> _numVipPrice;
		
		private System.Nullable<decimal> _numCost;
		
		private System.Nullable<decimal> _numCleanCost;
		
		private byte _intSaleState;
		
		private string _vchBrandName;
		
		private string _vchCateName;
		
		private string _vchCateChildName;
		
		private System.Nullable<int> _intScore;
		
		private decimal _numHerdPrice;
		
		private int _intChannelID;
		
		private short _intHerdID;
		
		private System.Nullable<int> _intWeight;
		
		private string _txtWebShowInfo;
		
		private System.Nullable<int> _intAreaID;
		
		private System.Nullable<int> _intStockQty;
		
		private string _vchShortName;
		
		private string _vchproductcode;
		
		private string _PromotionMemo;
		
		private System.Nullable<int> _intCommentVolume;
		
		private System.Nullable<int> _intSalesVolume;
		
		public Vi_Web_Pdt_Detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductName", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string vchProductName
		{
			get
			{
				return this._vchProductName;
			}
			set
			{
				if ((this._vchProductName != value))
				{
					this._vchProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMainPicURL", DbType="VarChar(128)")]
		public string vchMainPicURL
		{
			get
			{
				return this._vchMainPicURL;
			}
			set
			{
				if ((this._vchMainPicURL != value))
				{
					this._vchMainPicURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intProductID", DbType="Int NOT NULL")]
		public int intProductID
		{
			get
			{
				return this._intProductID;
			}
			set
			{
				if ((this._intProductID != value))
				{
					this._intProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intGroupID", DbType="Int")]
		public System.Nullable<int> intGroupID
		{
			get
			{
				return this._intGroupID;
			}
			set
			{
				if ((this._intGroupID != value))
				{
					this._intGroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsNew", DbType="Int")]
		public System.Nullable<int> intIsNew
		{
			get
			{
				return this._intIsNew;
			}
			set
			{
				if ((this._intIsNew != value))
				{
					this._intIsNew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsProm", DbType="Int")]
		public System.Nullable<int> intIsProm
		{
			get
			{
				return this._intIsProm;
			}
			set
			{
				if ((this._intIsProm != value))
				{
					this._intIsProm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intBrandID", DbType="Int NOT NULL")]
		public int intBrandID
		{
			get
			{
				return this._intBrandID;
			}
			set
			{
				if ((this._intBrandID != value))
				{
					this._intBrandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebType", DbType="Int NOT NULL")]
		public int intWebType
		{
			get
			{
				return this._intWebType;
			}
			set
			{
				if ((this._intWebType != value))
				{
					this._intWebType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebChildType", DbType="Int NOT NULL")]
		public int intWebChildType
		{
			get
			{
				return this._intWebChildType;
			}
			set
			{
				if ((this._intWebChildType != value))
				{
					this._intWebChildType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebThirdType", DbType="Int")]
		public System.Nullable<int> intWebThirdType
		{
			get
			{
				return this._intWebThirdType;
			}
			set
			{
				if ((this._intWebThirdType != value))
				{
					this._intWebThirdType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intFirstCategory", DbType="Int NOT NULL")]
		public int intFirstCategory
		{
			get
			{
				return this._intFirstCategory;
			}
			set
			{
				if ((this._intFirstCategory != value))
				{
					this._intFirstCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSecondCategory", DbType="Int NOT NULL")]
		public int intSecondCategory
		{
			get
			{
				return this._intSecondCategory;
			}
			set
			{
				if ((this._intSecondCategory != value))
				{
					this._intSecondCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intThreeCategory", DbType="Int NOT NULL")]
		public int intThreeCategory
		{
			get
			{
				return this._intThreeCategory;
			}
			set
			{
				if ((this._intThreeCategory != value))
				{
					this._intThreeCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intStartAge", DbType="SmallInt")]
		public System.Nullable<short> intStartAge
		{
			get
			{
				return this._intStartAge;
			}
			set
			{
				if ((this._intStartAge != value))
				{
					this._intStartAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intEndAge", DbType="SmallInt")]
		public System.Nullable<short> intEndAge
		{
			get
			{
				return this._intEndAge;
			}
			set
			{
				if ((this._intEndAge != value))
				{
					this._intEndAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProColr", DbType="NVarChar(32)")]
		public string vchProColr
		{
			get
			{
				return this._vchProColr;
			}
			set
			{
				if ((this._vchProColr != value))
				{
					this._vchProColr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchSpec", DbType="NVarChar(32)")]
		public string vchSpec
		{
			get
			{
				return this._vchSpec;
			}
			set
			{
				if ((this._vchSpec != value))
				{
					this._vchSpec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductPrinted", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string vchProductPrinted
		{
			get
			{
				return this._vchProductPrinted;
			}
			set
			{
				if ((this._vchProductPrinted != value))
				{
					this._vchProductPrinted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAttribute", DbType="Int NOT NULL")]
		public int intAttribute
		{
			get
			{
				return this._intAttribute;
			}
			set
			{
				if ((this._intAttribute != value))
				{
					this._intAttribute = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numMarketPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> numMarketPrice
		{
			get
			{
				return this._numMarketPrice;
			}
			set
			{
				if ((this._numMarketPrice != value))
				{
					this._numMarketPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numVipPrice", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> numVipPrice
		{
			get
			{
				return this._numVipPrice;
			}
			set
			{
				if ((this._numVipPrice != value))
				{
					this._numVipPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCost", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> numCost
		{
			get
			{
				return this._numCost;
			}
			set
			{
				if ((this._numCost != value))
				{
					this._numCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCleanCost", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> numCleanCost
		{
			get
			{
				return this._numCleanCost;
			}
			set
			{
				if ((this._numCleanCost != value))
				{
					this._numCleanCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSaleState", DbType="TinyInt NOT NULL")]
		public byte intSaleState
		{
			get
			{
				return this._intSaleState;
			}
			set
			{
				if ((this._intSaleState != value))
				{
					this._intSaleState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchBrandName", DbType="NVarChar(25)")]
		public string vchBrandName
		{
			get
			{
				return this._vchBrandName;
			}
			set
			{
				if ((this._vchBrandName != value))
				{
					this._vchBrandName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCateName", DbType="NVarChar(32)")]
		public string vchCateName
		{
			get
			{
				return this._vchCateName;
			}
			set
			{
				if ((this._vchCateName != value))
				{
					this._vchCateName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchCateChildName", DbType="NVarChar(32)")]
		public string vchCateChildName
		{
			get
			{
				return this._vchCateChildName;
			}
			set
			{
				if ((this._vchCateChildName != value))
				{
					this._vchCateChildName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intScore", DbType="Int")]
		public System.Nullable<int> intScore
		{
			get
			{
				return this._intScore;
			}
			set
			{
				if ((this._intScore != value))
				{
					this._intScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numHerdPrice", DbType="Decimal(10,2) NOT NULL")]
		public decimal numHerdPrice
		{
			get
			{
				return this._numHerdPrice;
			}
			set
			{
				if ((this._numHerdPrice != value))
				{
					this._numHerdPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intChannelID", DbType="Int NOT NULL")]
		public int intChannelID
		{
			get
			{
				return this._intChannelID;
			}
			set
			{
				if ((this._intChannelID != value))
				{
					this._intChannelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intHerdID", DbType="SmallInt NOT NULL")]
		public short intHerdID
		{
			get
			{
				return this._intHerdID;
			}
			set
			{
				if ((this._intHerdID != value))
				{
					this._intHerdID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWeight", DbType="Int")]
		public System.Nullable<int> intWeight
		{
			get
			{
				return this._intWeight;
			}
			set
			{
				if ((this._intWeight != value))
				{
					this._intWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtWebShowInfo", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string txtWebShowInfo
		{
			get
			{
				return this._txtWebShowInfo;
			}
			set
			{
				if ((this._txtWebShowInfo != value))
				{
					this._txtWebShowInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAreaID", DbType="Int")]
		public System.Nullable<int> intAreaID
		{
			get
			{
				return this._intAreaID;
			}
			set
			{
				if ((this._intAreaID != value))
				{
					this._intAreaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intStockQty", DbType="Int")]
		public System.Nullable<int> intStockQty
		{
			get
			{
				return this._intStockQty;
			}
			set
			{
				if ((this._intStockQty != value))
				{
					this._intStockQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchShortName", DbType="NVarChar(32)")]
		public string vchShortName
		{
			get
			{
				return this._vchShortName;
			}
			set
			{
				if ((this._vchShortName != value))
				{
					this._vchShortName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchproductcode", DbType="VarChar(50)")]
		public string vchproductcode
		{
			get
			{
				return this._vchproductcode;
			}
			set
			{
				if ((this._vchproductcode != value))
				{
					this._vchproductcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromotionMemo", DbType="VarChar(250)")]
		public string PromotionMemo
		{
			get
			{
				return this._PromotionMemo;
			}
			set
			{
				if ((this._PromotionMemo != value))
				{
					this._PromotionMemo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intCommentVolume", DbType="Int")]
		public System.Nullable<int> intCommentVolume
		{
			get
			{
				return this._intCommentVolume;
			}
			set
			{
				if ((this._intCommentVolume != value))
				{
					this._intCommentVolume = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSalesVolume", DbType="Int")]
		public System.Nullable<int> intSalesVolume
		{
			get
			{
				return this._intSalesVolume;
			}
			set
			{
				if ((this._intSalesVolume != value))
				{
					this._intSalesVolume = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pdt_Base_Info")]
	public partial class Pdt_Base_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _intProductID;
		
		private string _vchPorductNO;
		
		private string _vchProductPrinted;
		
		private string _vchProductFactoryNo;
		
		private string _vchProductName;
		
		private string _vchShortName;
		
		private int _intBrandID;
		
		private string _vchUnit;
		
		private string _vchSpec;
		
		private byte _intState;
		
		private int _intFirstCategory;
		
		private int _intSecondCategory;
		
		private int _intThreeCategory;
		
		private int _intWebType;
		
		private int _intWebChildType;
		
		private System.Nullable<byte> _intIsExpress;
		
		private int _intScoreMulriple;
		
		private string _vchBarCode;
		
		private string _vchKeyWords;
		
		private int _intAttribute;
		
		private System.Nullable<int> _intWeight;
		
		private string _vchMainPicURL;
		
		private string _vchPageURL;
		
		private System.Nullable<int> _intScore;
		
		private string _vchProductStunt;
		
		private System.Nullable<int> _intMajorProductID;
		
		private System.Nullable<int> _intGroupID;
		
		private System.Nullable<int> _intIsGroup;
		
		private System.Nullable<short> _intStartAge;
		
		private System.Nullable<short> _intEndAge;
		
		private string _vchProColr;
		
		private System.Nullable<int> _intIsProm;
		
		private System.Nullable<int> _intIsNew;
		
		private System.Nullable<int> _intWebThirdType;
		
		private string _vchproductcode;
		
		private string _vchTips;
		
		private string _PromotionMemo;
		
		private string _vchFxDescription;
		
		private System.Nullable<decimal> _numcost;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnintProductIDChanging(int value);
    partial void OnintProductIDChanged();
    partial void OnvchPorductNOChanging(string value);
    partial void OnvchPorductNOChanged();
    partial void OnvchProductPrintedChanging(string value);
    partial void OnvchProductPrintedChanged();
    partial void OnvchProductFactoryNoChanging(string value);
    partial void OnvchProductFactoryNoChanged();
    partial void OnvchProductNameChanging(string value);
    partial void OnvchProductNameChanged();
    partial void OnvchShortNameChanging(string value);
    partial void OnvchShortNameChanged();
    partial void OnintBrandIDChanging(int value);
    partial void OnintBrandIDChanged();
    partial void OnvchUnitChanging(string value);
    partial void OnvchUnitChanged();
    partial void OnvchSpecChanging(string value);
    partial void OnvchSpecChanged();
    partial void OnintStateChanging(byte value);
    partial void OnintStateChanged();
    partial void OnintFirstCategoryChanging(int value);
    partial void OnintFirstCategoryChanged();
    partial void OnintSecondCategoryChanging(int value);
    partial void OnintSecondCategoryChanged();
    partial void OnintThreeCategoryChanging(int value);
    partial void OnintThreeCategoryChanged();
    partial void OnintWebTypeChanging(int value);
    partial void OnintWebTypeChanged();
    partial void OnintWebChildTypeChanging(int value);
    partial void OnintWebChildTypeChanged();
    partial void OnintIsExpressChanging(System.Nullable<byte> value);
    partial void OnintIsExpressChanged();
    partial void OnintScoreMulripleChanging(int value);
    partial void OnintScoreMulripleChanged();
    partial void OnvchBarCodeChanging(string value);
    partial void OnvchBarCodeChanged();
    partial void OnvchKeyWordsChanging(string value);
    partial void OnvchKeyWordsChanged();
    partial void OnintAttributeChanging(int value);
    partial void OnintAttributeChanged();
    partial void OnintWeightChanging(System.Nullable<int> value);
    partial void OnintWeightChanged();
    partial void OnvchMainPicURLChanging(string value);
    partial void OnvchMainPicURLChanged();
    partial void OnvchPageURLChanging(string value);
    partial void OnvchPageURLChanged();
    partial void OnintScoreChanging(System.Nullable<int> value);
    partial void OnintScoreChanged();
    partial void OnvchProductStuntChanging(string value);
    partial void OnvchProductStuntChanged();
    partial void OnintMajorProductIDChanging(System.Nullable<int> value);
    partial void OnintMajorProductIDChanged();
    partial void OnintGroupIDChanging(System.Nullable<int> value);
    partial void OnintGroupIDChanged();
    partial void OnintIsGroupChanging(System.Nullable<int> value);
    partial void OnintIsGroupChanged();
    partial void OnintStartAgeChanging(System.Nullable<short> value);
    partial void OnintStartAgeChanged();
    partial void OnintEndAgeChanging(System.Nullable<short> value);
    partial void OnintEndAgeChanged();
    partial void OnvchProColrChanging(string value);
    partial void OnvchProColrChanged();
    partial void OnintIsPromChanging(System.Nullable<int> value);
    partial void OnintIsPromChanged();
    partial void OnintIsNewChanging(System.Nullable<int> value);
    partial void OnintIsNewChanged();
    partial void OnintWebThirdTypeChanging(System.Nullable<int> value);
    partial void OnintWebThirdTypeChanged();
    partial void OnvchproductcodeChanging(string value);
    partial void OnvchproductcodeChanged();
    partial void OnvchTipsChanging(string value);
    partial void OnvchTipsChanged();
    partial void OnPromotionMemoChanging(string value);
    partial void OnPromotionMemoChanged();
    partial void OnvchFxDescriptionChanging(string value);
    partial void OnvchFxDescriptionChanged();
    partial void OnnumcostChanging(System.Nullable<decimal> value);
    partial void OnnumcostChanged();
    #endregion
		
		public Pdt_Base_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intProductID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int intProductID
		{
			get
			{
				return this._intProductID;
			}
			set
			{
				if ((this._intProductID != value))
				{
					this.OnintProductIDChanging(value);
					this.SendPropertyChanging();
					this._intProductID = value;
					this.SendPropertyChanged("intProductID");
					this.OnintProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchPorductNO", DbType="VarChar(32)")]
		public string vchPorductNO
		{
			get
			{
				return this._vchPorductNO;
			}
			set
			{
				if ((this._vchPorductNO != value))
				{
					this.OnvchPorductNOChanging(value);
					this.SendPropertyChanging();
					this._vchPorductNO = value;
					this.SendPropertyChanged("vchPorductNO");
					this.OnvchPorductNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductPrinted", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string vchProductPrinted
		{
			get
			{
				return this._vchProductPrinted;
			}
			set
			{
				if ((this._vchProductPrinted != value))
				{
					this.OnvchProductPrintedChanging(value);
					this.SendPropertyChanging();
					this._vchProductPrinted = value;
					this.SendPropertyChanged("vchProductPrinted");
					this.OnvchProductPrintedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductFactoryNo", DbType="VarChar(64)")]
		public string vchProductFactoryNo
		{
			get
			{
				return this._vchProductFactoryNo;
			}
			set
			{
				if ((this._vchProductFactoryNo != value))
				{
					this.OnvchProductFactoryNoChanging(value);
					this.SendPropertyChanging();
					this._vchProductFactoryNo = value;
					this.SendPropertyChanged("vchProductFactoryNo");
					this.OnvchProductFactoryNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductName", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string vchProductName
		{
			get
			{
				return this._vchProductName;
			}
			set
			{
				if ((this._vchProductName != value))
				{
					this.OnvchProductNameChanging(value);
					this.SendPropertyChanging();
					this._vchProductName = value;
					this.SendPropertyChanged("vchProductName");
					this.OnvchProductNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchShortName", DbType="NVarChar(32)")]
		public string vchShortName
		{
			get
			{
				return this._vchShortName;
			}
			set
			{
				if ((this._vchShortName != value))
				{
					this.OnvchShortNameChanging(value);
					this.SendPropertyChanging();
					this._vchShortName = value;
					this.SendPropertyChanged("vchShortName");
					this.OnvchShortNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intBrandID", DbType="Int NOT NULL")]
		public int intBrandID
		{
			get
			{
				return this._intBrandID;
			}
			set
			{
				if ((this._intBrandID != value))
				{
					this.OnintBrandIDChanging(value);
					this.SendPropertyChanging();
					this._intBrandID = value;
					this.SendPropertyChanged("intBrandID");
					this.OnintBrandIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchUnit", DbType="NVarChar(32)")]
		public string vchUnit
		{
			get
			{
				return this._vchUnit;
			}
			set
			{
				if ((this._vchUnit != value))
				{
					this.OnvchUnitChanging(value);
					this.SendPropertyChanging();
					this._vchUnit = value;
					this.SendPropertyChanged("vchUnit");
					this.OnvchUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchSpec", DbType="NVarChar(32)")]
		public string vchSpec
		{
			get
			{
				return this._vchSpec;
			}
			set
			{
				if ((this._vchSpec != value))
				{
					this.OnvchSpecChanging(value);
					this.SendPropertyChanging();
					this._vchSpec = value;
					this.SendPropertyChanged("vchSpec");
					this.OnvchSpecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intState", DbType="TinyInt NOT NULL")]
		public byte intState
		{
			get
			{
				return this._intState;
			}
			set
			{
				if ((this._intState != value))
				{
					this.OnintStateChanging(value);
					this.SendPropertyChanging();
					this._intState = value;
					this.SendPropertyChanged("intState");
					this.OnintStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intFirstCategory", DbType="Int NOT NULL")]
		public int intFirstCategory
		{
			get
			{
				return this._intFirstCategory;
			}
			set
			{
				if ((this._intFirstCategory != value))
				{
					this.OnintFirstCategoryChanging(value);
					this.SendPropertyChanging();
					this._intFirstCategory = value;
					this.SendPropertyChanged("intFirstCategory");
					this.OnintFirstCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSecondCategory", DbType="Int NOT NULL")]
		public int intSecondCategory
		{
			get
			{
				return this._intSecondCategory;
			}
			set
			{
				if ((this._intSecondCategory != value))
				{
					this.OnintSecondCategoryChanging(value);
					this.SendPropertyChanging();
					this._intSecondCategory = value;
					this.SendPropertyChanged("intSecondCategory");
					this.OnintSecondCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intThreeCategory", DbType="Int NOT NULL")]
		public int intThreeCategory
		{
			get
			{
				return this._intThreeCategory;
			}
			set
			{
				if ((this._intThreeCategory != value))
				{
					this.OnintThreeCategoryChanging(value);
					this.SendPropertyChanging();
					this._intThreeCategory = value;
					this.SendPropertyChanged("intThreeCategory");
					this.OnintThreeCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebType", DbType="Int NOT NULL")]
		public int intWebType
		{
			get
			{
				return this._intWebType;
			}
			set
			{
				if ((this._intWebType != value))
				{
					this.OnintWebTypeChanging(value);
					this.SendPropertyChanging();
					this._intWebType = value;
					this.SendPropertyChanged("intWebType");
					this.OnintWebTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebChildType", DbType="Int NOT NULL")]
		public int intWebChildType
		{
			get
			{
				return this._intWebChildType;
			}
			set
			{
				if ((this._intWebChildType != value))
				{
					this.OnintWebChildTypeChanging(value);
					this.SendPropertyChanging();
					this._intWebChildType = value;
					this.SendPropertyChanged("intWebChildType");
					this.OnintWebChildTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsExpress", DbType="TinyInt")]
		public System.Nullable<byte> intIsExpress
		{
			get
			{
				return this._intIsExpress;
			}
			set
			{
				if ((this._intIsExpress != value))
				{
					this.OnintIsExpressChanging(value);
					this.SendPropertyChanging();
					this._intIsExpress = value;
					this.SendPropertyChanged("intIsExpress");
					this.OnintIsExpressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intScoreMulriple", DbType="Int NOT NULL")]
		public int intScoreMulriple
		{
			get
			{
				return this._intScoreMulriple;
			}
			set
			{
				if ((this._intScoreMulriple != value))
				{
					this.OnintScoreMulripleChanging(value);
					this.SendPropertyChanging();
					this._intScoreMulriple = value;
					this.SendPropertyChanged("intScoreMulriple");
					this.OnintScoreMulripleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchBarCode", DbType="VarChar(32)")]
		public string vchBarCode
		{
			get
			{
				return this._vchBarCode;
			}
			set
			{
				if ((this._vchBarCode != value))
				{
					this.OnvchBarCodeChanging(value);
					this.SendPropertyChanging();
					this._vchBarCode = value;
					this.SendPropertyChanged("vchBarCode");
					this.OnvchBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchKeyWords", DbType="NVarChar(128)")]
		public string vchKeyWords
		{
			get
			{
				return this._vchKeyWords;
			}
			set
			{
				if ((this._vchKeyWords != value))
				{
					this.OnvchKeyWordsChanging(value);
					this.SendPropertyChanging();
					this._vchKeyWords = value;
					this.SendPropertyChanged("vchKeyWords");
					this.OnvchKeyWordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intAttribute", DbType="Int NOT NULL")]
		public int intAttribute
		{
			get
			{
				return this._intAttribute;
			}
			set
			{
				if ((this._intAttribute != value))
				{
					this.OnintAttributeChanging(value);
					this.SendPropertyChanging();
					this._intAttribute = value;
					this.SendPropertyChanged("intAttribute");
					this.OnintAttributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWeight", DbType="Int")]
		public System.Nullable<int> intWeight
		{
			get
			{
				return this._intWeight;
			}
			set
			{
				if ((this._intWeight != value))
				{
					this.OnintWeightChanging(value);
					this.SendPropertyChanging();
					this._intWeight = value;
					this.SendPropertyChanged("intWeight");
					this.OnintWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchMainPicURL", DbType="VarChar(128)")]
		public string vchMainPicURL
		{
			get
			{
				return this._vchMainPicURL;
			}
			set
			{
				if ((this._vchMainPicURL != value))
				{
					this.OnvchMainPicURLChanging(value);
					this.SendPropertyChanging();
					this._vchMainPicURL = value;
					this.SendPropertyChanged("vchMainPicURL");
					this.OnvchMainPicURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchPageURL", DbType="VarChar(128)")]
		public string vchPageURL
		{
			get
			{
				return this._vchPageURL;
			}
			set
			{
				if ((this._vchPageURL != value))
				{
					this.OnvchPageURLChanging(value);
					this.SendPropertyChanging();
					this._vchPageURL = value;
					this.SendPropertyChanged("vchPageURL");
					this.OnvchPageURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intScore", DbType="Int")]
		public System.Nullable<int> intScore
		{
			get
			{
				return this._intScore;
			}
			set
			{
				if ((this._intScore != value))
				{
					this.OnintScoreChanging(value);
					this.SendPropertyChanging();
					this._intScore = value;
					this.SendPropertyChanged("intScore");
					this.OnintScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProductStunt", DbType="NVarChar(3000)")]
		public string vchProductStunt
		{
			get
			{
				return this._vchProductStunt;
			}
			set
			{
				if ((this._vchProductStunt != value))
				{
					this.OnvchProductStuntChanging(value);
					this.SendPropertyChanging();
					this._vchProductStunt = value;
					this.SendPropertyChanged("vchProductStunt");
					this.OnvchProductStuntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intMajorProductID", DbType="Int")]
		public System.Nullable<int> intMajorProductID
		{
			get
			{
				return this._intMajorProductID;
			}
			set
			{
				if ((this._intMajorProductID != value))
				{
					this.OnintMajorProductIDChanging(value);
					this.SendPropertyChanging();
					this._intMajorProductID = value;
					this.SendPropertyChanged("intMajorProductID");
					this.OnintMajorProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intGroupID", DbType="Int")]
		public System.Nullable<int> intGroupID
		{
			get
			{
				return this._intGroupID;
			}
			set
			{
				if ((this._intGroupID != value))
				{
					this.OnintGroupIDChanging(value);
					this.SendPropertyChanging();
					this._intGroupID = value;
					this.SendPropertyChanged("intGroupID");
					this.OnintGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsGroup", DbType="Int")]
		public System.Nullable<int> intIsGroup
		{
			get
			{
				return this._intIsGroup;
			}
			set
			{
				if ((this._intIsGroup != value))
				{
					this.OnintIsGroupChanging(value);
					this.SendPropertyChanging();
					this._intIsGroup = value;
					this.SendPropertyChanged("intIsGroup");
					this.OnintIsGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intStartAge", DbType="SmallInt")]
		public System.Nullable<short> intStartAge
		{
			get
			{
				return this._intStartAge;
			}
			set
			{
				if ((this._intStartAge != value))
				{
					this.OnintStartAgeChanging(value);
					this.SendPropertyChanging();
					this._intStartAge = value;
					this.SendPropertyChanged("intStartAge");
					this.OnintStartAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intEndAge", DbType="SmallInt")]
		public System.Nullable<short> intEndAge
		{
			get
			{
				return this._intEndAge;
			}
			set
			{
				if ((this._intEndAge != value))
				{
					this.OnintEndAgeChanging(value);
					this.SendPropertyChanging();
					this._intEndAge = value;
					this.SendPropertyChanged("intEndAge");
					this.OnintEndAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchProColr", DbType="NVarChar(32)")]
		public string vchProColr
		{
			get
			{
				return this._vchProColr;
			}
			set
			{
				if ((this._vchProColr != value))
				{
					this.OnvchProColrChanging(value);
					this.SendPropertyChanging();
					this._vchProColr = value;
					this.SendPropertyChanged("vchProColr");
					this.OnvchProColrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsProm", DbType="Int")]
		public System.Nullable<int> intIsProm
		{
			get
			{
				return this._intIsProm;
			}
			set
			{
				if ((this._intIsProm != value))
				{
					this.OnintIsPromChanging(value);
					this.SendPropertyChanging();
					this._intIsProm = value;
					this.SendPropertyChanged("intIsProm");
					this.OnintIsPromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intIsNew", DbType="Int")]
		public System.Nullable<int> intIsNew
		{
			get
			{
				return this._intIsNew;
			}
			set
			{
				if ((this._intIsNew != value))
				{
					this.OnintIsNewChanging(value);
					this.SendPropertyChanging();
					this._intIsNew = value;
					this.SendPropertyChanged("intIsNew");
					this.OnintIsNewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intWebThirdType", DbType="Int")]
		public System.Nullable<int> intWebThirdType
		{
			get
			{
				return this._intWebThirdType;
			}
			set
			{
				if ((this._intWebThirdType != value))
				{
					this.OnintWebThirdTypeChanging(value);
					this.SendPropertyChanging();
					this._intWebThirdType = value;
					this.SendPropertyChanged("intWebThirdType");
					this.OnintWebThirdTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchproductcode", DbType="VarChar(50)")]
		public string vchproductcode
		{
			get
			{
				return this._vchproductcode;
			}
			set
			{
				if ((this._vchproductcode != value))
				{
					this.OnvchproductcodeChanging(value);
					this.SendPropertyChanging();
					this._vchproductcode = value;
					this.SendPropertyChanged("vchproductcode");
					this.OnvchproductcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchTips", DbType="VarChar(50)")]
		public string vchTips
		{
			get
			{
				return this._vchTips;
			}
			set
			{
				if ((this._vchTips != value))
				{
					this.OnvchTipsChanging(value);
					this.SendPropertyChanging();
					this._vchTips = value;
					this.SendPropertyChanged("vchTips");
					this.OnvchTipsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromotionMemo", DbType="VarChar(250)")]
		public string PromotionMemo
		{
			get
			{
				return this._PromotionMemo;
			}
			set
			{
				if ((this._PromotionMemo != value))
				{
					this.OnPromotionMemoChanging(value);
					this.SendPropertyChanging();
					this._PromotionMemo = value;
					this.SendPropertyChanged("PromotionMemo");
					this.OnPromotionMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vchFxDescription", DbType="VarChar(50)")]
		public string vchFxDescription
		{
			get
			{
				return this._vchFxDescription;
			}
			set
			{
				if ((this._vchFxDescription != value))
				{
					this.OnvchFxDescriptionChanging(value);
					this.SendPropertyChanging();
					this._vchFxDescription = value;
					this.SendPropertyChanged("vchFxDescription");
					this.OnvchFxDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numcost", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> numcost
		{
			get
			{
				return this._numcost;
			}
			set
			{
				if ((this._numcost != value))
				{
					this.OnnumcostChanging(value);
					this.SendPropertyChanging();
					this._numcost = value;
					this.SendPropertyChanged("numcost");
					this.OnnumcostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
